### ISSUE TITLE
Authorization Server Errors

### ISSUE THREAD

**Issue by alhan-dfds** [articulate/terraform-provider-okta#299] opened 2019-10-14 13:27 UTC
Hey,
I am trying to create a module, where I send a list of apps to create, which creates a app and authserver, this code

module clients {
  source     = "./terraform_modules/selfservice_clients"
  clients = [{ 
    name  = "selfservice_client_1"
    scopes   = ["selfservice_client_1.read", "selfservice_client_1.write"]
  }
  ,
  { 
    name  = "selfservice_client_2"
    scopes   = ["selfservice_client_2.read", "selfservice_client_2.write"]
  }
]

variable clients {
    description = "list of clients"
    type = list(
      object({
      name = string
      scopes= list(string) 
    }))
    default     = []
}

resource okta_app_oauth selfservice_app_auth {
    count = length(var.clients)
    label = var.clients[count.index].name
    type  = "service"
    redirect_uris= []
    response_types= [
      "token"
    ]
    grant_types= [
      "client_credentials"
    ]  
    token_endpoint_auth_method= "client_secret_basic"  
}

resource okta_auth_server selfservice_auth_server {
  count = length(okta_app_oauth.selfservice_app_auth)
  name        = "${okta_app_oauth.selfservice_app_auth[count.index].label}"  
  audiences   = ["api://${okta_app_oauth.selfservice_app_auth[count.index].label}"]
  depends_on = [okta_app_oauth.selfservice_app_auth] 
}
But I get this error
[crash.log](https://github.com/articulate/terraform-provider-okta/files/3724591/crash.log)

**Comment by alhan-dfds** [comment] 2019-10-14 13:34
I can see that the "Last rotation" hasnt been set on the second auth server
![image](https://user-images.githubusercontent.com/50141679/66755370-22ee6800-ee98-11e9-9311-4b3ef93a058a.png)

**Comment by alhan-dfds** [comment] 2019-10-14 14:06
I can also reproduce the same error, with this code



resource okta_app_oauth selfservice_app_auth {
    count = length(var.clients)
    label = var.clients[count.index].name
    type  = "service"
    redirect_uris= []
    response_types= [
      "token"
    ]
    grant_types= [
      "client_credentials"
    ]  
    token_endpoint_auth_method= "client_secret_basic"  
}

resource okta_auth_server selfservice_auth_server_1 {  
  name        = "selfservice_client_1"  
  audiences   = ["api://selfservice_client_1"]
  depends_on = [okta_app_oauth.selfservice_app_auth] 
  }

resource okta_auth_server selfservice_auth_server_2 {  
  name        = "selfservice_client_2"  
  audiences   = ["api://selfservice_client_2"]
  depends_on = [okta_app_oauth.selfservice_app_auth] 
}

**Comment by alhan-dfds** [comment] 2019-10-14 14:25
Defintly a timing bug, cause this code works
resource okta_auth_server selfservice_auth_server_1 {  
   provisioner "local-exec" {
    command = "sleep 40"
  }
  name        = "selfservice_client_1"  
  audiences   = ["api://selfservice_client_1"]

  }
resource okta_auth_server selfservice_auth_server_2 {  
  name        = "selfservice_client_2"  
  audiences   = ["api://selfservice_client_2"]
    depends_on = [okta_auth_server.selfservice_auth_server_1] 
}

**Comment by quantumew** [comment] 2019-10-14 15:12
On certain endpoints Okta responds to POST requests with a 200, which really just denotes that they have queued your creation request, and it will subsequently actually create the resource. Often if you attempt to create another resource that depends on this resource, it will fail with some bizarre errors. There is really not much the provider can do about this. Okta responds with errors that aren't considered "retryable", even though they created a unique identifier for this resource already, I should be able to reference it, or they should return an error that is distinct and I can retry on. With that said we shouldn't be panicking, that looks like a bug. I will also shoot an email to Okta's engineering, I need to ask them how are we supposed to automate around this, other than putting sleeps in here or there or building some sort of polling logic in the provider, which will drain consumers rate limits.

**Comment by alhan-dfds** [comment] 2019-10-15 06:56
Well I think you need the provider more robust, for these things, otherwise it is kinda hard to use in large scale, where you have to provision lots of entities in to Okta.
As I consumer of the provider, I am in an even worse place, since I cant really do anything about this. Since it is the provider that cast an exception.
But keep me updated with the responds from Okta, please.

**Comment by alhan-dfds** [comment] 2019-10-15 07:46
How you sleep between each creation of a resource.
Cause this still fail, with same error:

resource okta_auth_server selfservice_auth_server {
   provisioner "local-exec" {
     command = "sleep 30"
   }
  count = 2
  name        = "selfservice_auth_server_${count.index}"  
  audiences   = ["api://selfservice_auth_server_${count.index}"]
}

**Comment by quantumew** [comment] 2019-10-15 10:20
To be clear, the panic is unrelated that is likely a bug which can be prevented once I look into it. The Okta API not actually creating resources in real time with some resources  causing a gap where you can associate the resource is a bit harder to solve right and not a terribly common scenario thus it hasn’t been thoroughly dug into yet. The way to solve it in the current state is to hit Okta’s api and pause execution until a thing exists, which I would like to avoid because of rate limits.

**Comment by quantumew** [comment] 2019-10-15 10:20
Going to look into this today

**Comment by alhan-dfds** [comment] 2019-10-15 10:22
Awesome=) I appreciate it. Maybe you can put in a property, if you want to have the slower provision, but will make sure that the resource exist?

**Comment by quantumew** [comment] 2019-10-15 14:08
Ok weird, this had nothing to do with eventual consistency, although the symptoms look just like it. Fix on its way. Why the sleep work is still puzzling to me. That may have been a fluke. Once I get the PR merged I will have you try the new version and report back. I added test with your exact config and it worked for me.

**Comment by alhan-dfds** [comment] 2019-10-16 07:30
Let me know when to test, cause I just reproduced it 10 times on this.

resource okta_auth_server selfservice_auth_server {
   provisioner "local-exec" {
     command = "sleep 30"
   }
  count = 2
  name        = "selfservice_auth_server_${count.index}"  
  audiences   = ["api://selfservice_auth_server_${count.index}"]
}

**Comment by quantumew** [comment] 2019-10-16 11:42
You just need to pull down the latest release or rebuild the provider to test this. Please confirm the version of the provider you are running.

**Comment by alhan-dfds** [comment] 2019-10-16 11:46
Could you guide me through this?=) I am still a little new to terraform...

**Comment by alhan-dfds** [comment] 2019-10-16 11:50
Terraform v0.12.10
+ provider.aws v2.31.0
+ provider.okta v3.0.28

**Comment by quantumew** [comment] 2019-10-16 11:52
Sure, you want v3.0.29 with the bug fix. You can go to the releases for this repo, find the latest release, and download the binary for you OS architecture. Once you have that you will want to delete the old provider binary and move the new on into its place. See the link below for where Terraform wants you to put your provider binaries.

https://www.terraform.io/docs/plugins/basics.html

**Comment by alhan-dfds** [comment] 2019-10-16 12:54
It is working now, when I am doing it directly from Windows. Struggling with the docker-compose upgrade...will get back to you when I get that working

**Comment by alhan-dfds** [comment] 2019-10-16 13:04
It is working now, both from windows and from docker-compose setup. So thanks for the quick fix...

**Comment by quantumew** [comment] 2019-10-16 13:07
Awesome! Once the provider is official you won’t have to manually download it like that again. Terraform will pull it from the registry. Sorry for the earlier confusion, glad I could help.

**Comment by alhan-dfds** [comment] 2019-10-18 08:53
Hey man,
I am actually running in issues, where the second auth server isnt created correct. It is missing "Last rotation"

![image](https://user-images.githubusercontent.com/50141679/67080434-8678de00-f195-11e9-91bc-03d19becf96e.png)

**Comment by alhan-dfds** [comment] 2019-10-18 09:10
I had to add timer for 3 min to make sure it was ready and created correct

provisioner "local-exec" {
    command = "sleep 200" 
  }

**Comment by alhan-dfds** [comment] 2019-10-18 10:57
Now it is failing after waiting for 500 seconds before doing other stuff to the auth server.

**Comment by alhan-dfds** [comment] 2019-10-18 11:00
It fails like this

Error: The API returned an error: Internal Server Error

  on terraform_modules/selfservice_clients/main.tf line 64, in resource "okta_auth_server_scope" "selfservice_auth_server_scope":
  64: resource okta_auth_server_scope selfservice_auth_server_scope {

**Comment by quantumew** [comment] 2019-10-18 12:28
Hey  @alhan-dfds, Can you send me the exact config to repro? Would this config repro it? https://github.com/articulate/terraform-provider-okta/blob/master/examples/okta_auth_server/dependency.tf

 I am guessing it is an intermittent issue oddly enough and the sleep is just a red herring. I am going to reopen this for now. Also, just as an aside, I was only hitting this error before I fixed that bug in v3.0.29, can you confirm your version again? Just in case 😄

**Comment by alhan-dfds** [comment] 2019-10-21 05:25
Yes I can confirm I am on v3.0.29.
+ provider.aws v2.32.0
+ provider.null v2.1.2
+ provider.okta v3.0.29

It fixed it when creatíng multiple auth server. The problem occurs when I do other stuff on the newly created auth server just after...
As you in attached file, I create 2 app, 2 auth servers, and add a policies and scopes.
1/3 times the script works, but the other times it fails with the "The API returned an error: Internal Server Error"

See attached zip for the setup.

[Okta selfservice_client.zip](https://github.com/articulate/terraform-provider-okta/files/3749124/Okta.selfservice_client.zip)

**Comment by quantumew** [comment] 2019-10-21 12:29
@alhan-dfds perfect I will replicate this in a test and get back to you. Thanks!

**Comment by alhan-dfds** [comment] 2019-10-23 09:10
Hey=) can you reproduce it?

**Comment by quantumew** [comment] 2019-10-23 12:18
@alhan-dfds trying now

**Comment by quantumew** [comment] 2019-10-23 12:46
@alhan-dfds I boiled down your test to the basic elements (without the sleep) and was able to run it 10 times without issue (with test cache off of course). See the commit above and let me know if you see I am missing anything. I have a few questions below for you. Please note your can run this with debug logs `TF_LOG=debug` to dump all of the request/responses. If you post them here please redact your API token or rotate it. This will allow us to grab the request id and report it to Okta. Then they can tell us wtf is intermittently blowing up.  

- When this occurs is it during a plan or apply? Are the resources existing resources or is this a new plan?
- It appears it happens with the scope, is it during a read, create, or update?
- We have considered the idea this was caused by Okta's eventual consistency, i.e. Okta takes a while to do what we tell it to despite the successful response. If this was true, a sleep would allow this to be successful every time, have you seen this? If this error occurs despite the sleep I think we can rule this out as the cause.

**Comment by alhan-dfds** [comment] 2019-10-23 13:18
I just ran it in docker-compose and on windows. And everything is working now everytime without a sleep. I did this 20 times last week, failing everytime=( but looks like it is fixed now. Hope they fixed something and not a sporadic error...

**Comment by quantumew** [comment] 2019-10-23 13:21
Cool going to close this. This is likely an Okta API bug. If it comes up again let's extract the request id and report it to Okta. Thanks!

**Closed by quantumew** 2019-10-23 13:21 UTC
Labels: Investigation

**Comment by alhan-dfds** [comment] 2019-10-23 13:34
Yes, I will track the error next time. If it occurs.
