### ISSUE TITLE
User schema properties overwritten

### ISSUE THREAD

**Issue by quantumew** [articulate/terraform-provider-okta#144] opened 2019-04-24 14:03 UTC
When creating/updating multiple user schema properties we are seeing successful create and update responses but then later when we do a GET, the data is missing. The only way around this is by forcing creates/updates to happen one at a time. This appears to be a race condition in the API.

**Comment by hgibsonqb** [comment] 2019-05-06 16:54
I'm also having this issue

**Comment by quantumew** [comment] 2019-07-12 17:39
Did a little testing here and I think I see what is happening. It appears Okta is not returning the new schema right away. I am wondering if just sending Cache-Control no-cache will fix this? Another thing, is we are using the old SDK for this, we should probably update it to the new approach.

**Comment by msmrnv1** [comment] 2019-07-31 14:52
I am still seeing the issue when I try to create more than one custom field in the user schema. It works fine when it is just one custom field but it usually crashes when I create more than 1 custom field.

It looks like it is still getting nil after sleep function and getSubchema call

			time.Sleep(time.Second * 3)
			subschema, err = getSubSchema(d, m)

**Comment by quantumew** [comment] 2019-07-31 16:07
Interesting I tested it quite a lot with no issues. How often have you hit this?

I actually got to chat with Okta about this and it might be related to their API lying to us. Saying it is created when it actually was just queued up to be created. This is definitely just a bandage until they attend to that issue. I will dig into it a bit more.

**Comment by quantumew** [comment] 2019-07-31 16:10
I should also say, this should no longer panic, it should now simply error, if it is panicking that should be corrected anyways. Let me validate that. Also if you could validate the version of the provider you are using? Guessing the latest!

**Comment by msmrnv1** [comment] 2019-08-01 00:59
Yes, it was still panicking and it happens almost every time. I changed a bit in the fork to check for nil condition for schema to avoid the panicking. Only err was checked in that block.

		if subschema == nil {
			return fmt.Errorf("error getting resource %s: %s", d.Id(), err)
		}

**Comment by quantumew** [comment] 2019-08-01 01:56
Seriously, I forgot the gaurd statement lmao. Ok adding that. Will follow up and dig into why that is not working. Was this on Update? Or Create? Multiple schema properties?

**Comment by quantumew** [comment] 2019-08-01 02:00
Ok corrected in v3.0.12. Should have time this weekend to dig in further to this one.

**Comment by msmrnv1** [comment] 2019-08-01 02:27
It was on create. Below a sample of what I have in tf file

resource "okta_user_schema" "schema_uuid" {
  index       = "UserUuid"
  title       = "User UUID"
  type        = "string"
  description = "The internal user identifier"
  required    = false
  min_length  = 1
  max_length  = 50
  }

resource "okta_user_schema" "schema_fb" {
  index       = "facebookLinkingId"
  title       = "External Facebook Identifier"
  type        = "string"
  description = "External SSO Identifier for Facebook"
  required    = false
  min_length  = 1
  max_length  = 50
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
}

resource "okta_user_schema" "schema_ros" {
  index       = "rosLinkingId"
  title       = "External Ros Identifier"
  type        = "string"
  description = "External SSO Identifier for Ros"
  required    = false
  min_length  = 1
  max_length  = 50
  permissions = "READ_ONLY"
  master      = "PROFILE_MASTER"
}

Also, I tried to debug by turning on the trace log in terraform. I saw something like below... Do you know if it's an issue and how it fix it?



2019/07/31 20:51:09 [WARN] Provider "okta" produced an invalid plan for okta_schema.schema_uuid, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .permissions: planned value cty.StringVal("READ_ONLY") does not match config value cty.NullVal(cty.String)

**Comment by quantumew** [comment] 2019-08-01 13:08
Ok I think I figured out what is happening here. It looks like having multiple schema objects, due to the way the endpoint works, are conflicting. Fix coming soon. I may create a new resource that combines the entire schema into a single resource.

**Comment by quantumew** [comment] 2019-08-18 20:24
Finally got around to this one and I confirmed resource get overwritten when concurrent requests are sent to Okta's API. Opening an issue with Okta, for now we can use `depends_on` to ensure any new resources are created one at a time.  See #247 for the updated example: https://github.com/articulate/terraform-provider-okta/blob/af2012d239093fe64201663ac89182df8160b13c/examples/okta_user/custom_attributes.tf

I also started a new resource that would contain the entire schema to ensure resources are created one at a time. I will still finish this resources soon but there are downsides to this approach. You have to track the entire schema if you choose this approach. Obviously that is undesirable in some cases.

**Comment by msmrnv1** [comment] 2019-08-19 14:02
Thanks for an update. That is what I have been using as a work around. I had to create explicit dependency for each custom field so it works now.

**Comment by quantumew** [comment] 2019-08-30 18:46
This makes zero sense. I spoke with Okta support, and it sounds like this is just how the API works. It is batching the requests and only taking the final change, even though it is reporting back that it is taking the previous changes as well. Even though these are individual requests for individual distinct properties.

**Comment by jralmaraz** [comment] 2019-11-14 05:55
Hey, just checking if we did have any update on this or the only way going forward is by using the depends_on (which seems to working well for us, just slowing things down a little bit) ?

I thought of raising that with Okta, but better checking for the latest on it before :)

**Comment by quantumew** [comment] 2019-11-14 14:43
This is still just a feature request. Imo this is a bug in the API but they disagree. The solution currently is to turn off parallelism or add dependencies between these resources to avoid concurrency. I toyed with the idea of making a new resource but then you have to track the entire schema. I suppose I could add a “ignore_absent” option. Hmm that Might be an OK option. Worth looking into. It would have limitations though.

**Closed** 2020-03-18 20:46 UTC
Labels: blocked
